export const CREATE_RENTAL_CARD_REQUEST = "CREATE_RENTAL_CARD_REQUEST";
export const CREATE_RENTAL_CARD_SUCCESS = "CREATE_RENTAL_CARD_SUCCESS";
export const CREATE_RENTAL_CARD_FAIL = "CREATE_RENTAL_CARD_REQUEST";
export const CREATE_BILL_REQUEST = "CREATE_BILL_REQUEST";
export const CREATE_BILL_SUCCESS = "CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAIL = "CREATE_BILL_FAIL";
