export const GET_ALL_ROOMS_REQUEST = "GET_ALL_ROOMS_REQUEST";
export const GET_ALL_ROOMS_SUCCESS = "GET_ALL_ROOMS_SUCCESS";
export const GET_ALL_ROOMS_FAIL = "GET_ALL_ROOMS_FAIL";
export const GET_ROOM_DETAILS_REQUEST = "GET_ROOM_DETAILS_REQUEST";
export const GET_ROOM_DETAILS_SUCCESS = "GET_ROOM_DETAILS_SUCCESS";
export const GET_ROOM_DETAILS_FAIL = "GET_ROOM_DETAILS_FAIL";
